name: Nafis Zaman
title: nafis.dev
author: Nafis Zaman
email: nafzam@outlook.com
description: Nafis develops things
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-sitemap

# Theme
theme: minima
twitter_username: navzam
github_username: navzam
linkedin_username: nafiszaman
show_excerpts: true
excerpt_separator: <!--more-->

# Files to exclude from site
exclude:
  - README
  - CNAME
  - Gemfile
  - Gemfile.lock

# Custom variables
images_path: /assets/images/